# Please read the documentation found at https://goreleaser.com
#
project_name: duat

release:
  draft: true
  prerelease: auto

builds:
  - id: github-release
    dir: cmd/github-release
    binary: github-release
    tags:
    - osusergo
    - netgo
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    ldflags:
      - -extldflags=static
      - -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: license-detector
    dir: cmd/license-detector
    binary: license-detector
    tags:
    - osusergo
    - netgo
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    ldflags:
      - -extldflags=static
      - -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: semver
    dir: cmd/semver
    binary: semver
    tags:
    - osusergo
    - netgo
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    ldflags:
      - -extldflags=static
      - -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: stencil
    dir: cmd/stencil
    binary: stencil
    tags:
    - osusergo
    - netgo
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    ldflags:
      - -extldflags=static
      - -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: artifact
    dir: example/artifact
    binary: artifact
    tags:
    - osusergo
    - netgo
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    ldflags:
      - -extldflags=static
      - -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
    files:
        - none*
    format: gz

gomod:
  proxy: true
  mod: mod
