---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-config
  namespace: {{ .Namespace }}
type: Opaque
data:
    registry.yaml: '{{ expandenv "$Registry" | b64enc }}'
---
apiVersion: v1
kind: Secret
metadata:
  name: release-github-token
  namespace: {{ .Namespace }}
type: Opaque
data:
  github_token: '{{ expandenv "$GITHUB_TOKEN" | b64enc }}'
