From alpine

MAINTAINER Karl Mutch <karlmutch@gmail.com>

ADD bin/artifact .
CMD bin/artifact

LABEL karlmutch.duat.module.version=<repo-version></repo-version> \
      karlmutch.duat.module.name=github.com/karlmutch/duat/example/artifact
